# Generated by Django 2.1.3 on 2018-12-28 08:36

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=100)),
                ('detail', tinymce.models.HTMLField()),
                ('img', models.ImageField(upload_to='goods/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('unit', models.CharField(max_length=10)),
                ('visits', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('cag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Cag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
